### ISSUE TITLE
Deployment checklist

### ISSUE THREAD

**Issue by dan-gamble** [futily/futily#124]
## SEO

* [x] Page titles are correct
* [x] Meta description is working
* [x] OG parts are working
* [x] Twitter parts are working
* [ ] Responsive has been done
* [ ] Footer has been tied up
* [x] Sort OSM sitemap tools

## Misc

* [x] Login system works
* [x] Register system works
* [x] New fifa account needs to be bought to get the SBC data
* [ ] Need to set up a management command that gets the SBC stuff for live
* [ ] General feature testing
* [x] Squad builder slot background
* [ ] Copy for empty states
* [ ] Copy for homepage

## Services

* [x] Google analytics is hooked up
* [ ] Google adsense is hooked up
* [x] Add google webmaster tools
* [ ] Price system is working
* [x] Set up Cloudflare
* [ ] Set up backup system
